name = "repo-eval-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "REPO_EVAL_KV"
id = "<your_kv_namespace_id>"
preview_id = "<your_kv_preview_id>"

[[workflows]]
binding = "ORCHESTRATOR_WORKFLOW"
class = "OrchestratorWorkflow"
